# Maps dataloader inputs to model inputs and outputs
label_dir: 'human_entity_labels'
split: 'human_eval_labels'

cfg_scale: 8.0
default_denoising_steps: 50
mask_tp_threshold: 0.5


### BEGIN DATASET CONFIGURATION
dataset_cfg_kwargs:
  fload_keys: [
    "path_label_meta"
  ]

  load_cfgs: 
    - name: 'path_label_meta'
      type: 'dict'
      kwargs:
        subkeys:
          - name: 'paths_2d'
            dtype: 'float'
            dimensions: [10, 200, 2] # Max 10 path options @ 200 samples
          - name: 'goal_masks'
            key_name: 'target_segment'
            dtype: 'float'
            dimensions: [10, 288, 512]
            range: [-1, 1]
          - name: 'goals'
            dtype: 'str'
            dimensions: [10]
### END DATASET CONFIGURATION

### BEGIN MODEL INJECTION
# model_cfg_kwargs:
#   dataloader_inputs:
#   - in_key: "paths_2d"
#     out_key: "multipath_center_label"
#   - in_key: "goals"
#     out_key: "multigoal_command"

### END MODEL INJECTION


metrics:
  coverage:
    out_key: 'goal_image'
    enabled: True
    heading_range: [-60, 60]
    ensemble_size: 10 # Bump this up for more thorough evaluation of coverage
    steps: 3
  # robustness:
  #   out_key: 'goal_image'
  #   enabled: True
  #   ensemble_size: 10
  #   range: [0, 180]
  #   buckets: 20