model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_start: 30000
        disc_num_layers: 3
        disc_in_channels: 3
        disc_factor: 1.0
        disc_weight: 0.8
        codebook_weight: 1.0
        pixelloss_weight: 1.0
        perceptual_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 4
    train:
      target: data.imagenet_full_custom.ImageNetFullCustomTrain
      params:
        train_root: /scratch/sbeeredd/imagenet/ILSVRC/Data/CLS-LOC/train
        val_root: /scratch/sbeeredd/imagenet/ILSVRC/Data/CLS-LOC/val
        size: 256
    validation:
      target: data.imagenet_full_custom.ImageNetFullCustomValidation
      params:
        train_root: /scratch/sbeeredd/imagenet/ILSVRC/Data/CLS-LOC/train
        val_root: /scratch/sbeeredd/imagenet/ILSVRC/Data/CLS-LOC/val
        size: 256

lightning:
  logger:
    target: pytorch_lightning.loggers.WandbLogger
    params:
      name: vqgan_baseline_imagenet_256
      project: vqgan-imagenet
      save_dir: logs
      log_model: false
  
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False

  trainer:
    max_epochs: 100
    accumulate_grad_batches: 16
    gradient_clip_val: 1.0
