root_dir: "data/frodobots8k"
out_dir: "data/strict_frodobots8k_processed"

window_length: 400 # frames (20 seconds at 20 fps)
num_viz_samples: 100 # Set to -1 to visualize all samples (not recommended)

# Stage 1: Data Filtering
# pipeline:
#   download_maps: False        # Downloads .osm.pbf files (not necessary)
#   download_routing: True     # Enables route downloading (Set to True on first run)
#   apply_filters: True         # Applies the filters defined below  (Set to True on first run)
#   download_imagery: False     # Downloads satellite imagery
#   visualize_samples: False     # Visualizes some samples after filtering (Set to True When Debug)
#   sample_splits: False

# Stage 2: Split Sampling
pipeline:
  download_maps: False          # Downloads .osm.pbf files (not necessary)
  download_routing: False       # Enables route downloading (Set to True on first run)
  apply_filters: False         # Applies the filters defined below  (Set to True on first run)
  download_imagery: True        # Downloads satellite imagery
  visualize_samples: True     # Visualizes some samples after filtering (Set to True When Debug)
  sample_splits: False


download_maps:
  metadata_subdir: "maps/metadata"
  tile_subdir: "maps/tiles"     # Not used for now
  graph_subdir: "maps/graphs"
  graph_lut_path: "maps/metadata/ride_to_graph.csv"
  use_cache: True               # CAREFUL, set to false if data has changed!
  viz_clusters: False            # Takes a long time, but useful for debugging
  padding: 50.0                 # meters
  max_points_per_ride: 200      # points
  min_samples_per_cluster: 100  # points
  subsample_tol: 10.0           # meters for sampling road network

filters:
  - name: "time_filter"
    type: "time"
    params:
      max_desync: 1.0 # seconds
      time_range: ["08:00:00", "17:00:00"]   # Allowable time range
  - name: "intersection_filter"
    type: "gps"
    params:
      distance: 10.0 # meters
  # - name: "color_filter" # Too slow and memory intensive
  #   type: "image"
  #   params:
  #     brightness_threshold: [0.1, 0.9] # 10% to 90% brightness
  #     homogeneous_threshold: 0.7 # 70% image is same color
  - name: "image_filter"
    type: "image"
    params:
      resolutions: [
        [576, 1024]
      ] # Resize images to this size
  - name: "velocity_filter"
    type: "controls"
    effect: "remove"
    params:
      low_pass_window: 10 # 10 frames @ 10 hz ~1 seconds
      linear_velocity: [0.5, 1.0] # True min/max is -1, 1
      angular_velocity: [-0.25, 0.25] # True min/max is -1,1