robot_name: ferrite7
frame_rate: 15 # Hz
image_height: 240
image_width: 320
visualize_path: True
save_plan: False

path_smoothing:
  enable: False
  window_size: 3 # Number of past actions to consider for smoothing

camera_topic:       "/{ROBOT_NAME}/camera_front/color/image_raw/compressed"
# depth_topic:        "/{ROBOT_NAME}/camera_front/aligned_depth_to_color/image_raw/compressed"
cloud_topic:       "/{ROBOT_NAME}/raw_velodyne_points"
camera_info_topic:  "/{ROBOT_NAME}/camera_front/color/camera_info"
odom_topic:         "/{ROBOT_NAME}/lo_frontend/odometry"
# tf_topic:          "/{ROBOT_NAME}/tf"
tf_topic:          "/tf"

image_plan_topic:   "/{ROBOT_NAME}/spinflow/path_image/offline"
action_topic:       "/{ROBOT_NAME}/spinflow/local_planner/plan/offline" 

odom_frame: "{ROBOT_NAME}/odom"
optical_frame: "{ROBOT_NAME}/camera_front/camera_color_optical_frame"
base_link_frame: "{ROBOT_NAME}/base_link"
